# docs:
# https://docs.gitlab.com/ee/ci/yaml/
# linter:
# https://gitlab.com/ci/lint

stages:
    - install
    - test
    - build
    - deploy
    
image: node:9    
    
npm-install:
    stage: install
    script:
        - npm install
    artifacts:
        paths:
            - node_modules

lint:
    stage: test
    script:
        - npm run lint

stylelint:
    stage: test
    script:
        - npm run stylelint
        
unit:
    stage: test
    script:
        - npm run unit
    artifacts:
        paths:
            - test\unit\coverage
            
build:
    stage: build
    script:
        - npm run build
    artifacts:
        paths:
            - dist     